theme: jekyll-theme-architect

markdown: kramdown
title: "Cadet Workpage"
email: courtney.cowper@altamiracorp.com
navbar:
left:
- text: "Home"
  href: index.html
- text: "Calendar"
  href: calendar.html
- text: "Syllabus"
  href: syllabus.html
- text: "Slides"
  menu:
  - text: "Module 1"

